[package]
name = "esp-wlan-led-matrix-client"
description = "Control an espPixelmatrix via Rust"
version = "0.1.0"
license = "MIT"
repository = "https://github.com/EdJoPaTo/esp-wlan-led-matrix-client"
authors = ["EdJoPaTo <esp-wlan-led-matrix-client-rust@edjopato.de>"]
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
# See https://doc.rust-lang.org/rustc/codegen-options/index.html
codegen-units = 1
lto = true

[features]
default = ["sync", "async-tokio"]
sync = ["bufstream"]
async-tokio = ["tokio"]
embedded-graphics-impl = ["embedded-graphics", "sync"]

[[example]]
name = "fill"
required-features = ["sync"]

[[example]]
name = "rectangle"
required-features = ["sync"]

[[example]]
name = "snake"
required-features = ["sync"]

[[example]]
name = "speedtest"
required-features = ["sync"]

[[example]]
name = "stars"
required-features = ["async-tokio"]

[dependencies]

[dependencies.bufstream]
version = "0.1"
optional = true

[dependencies.embedded-graphics]
version = "0.7"
optional = true

[dependencies.tokio]
version = "1"
optional = true
features = ["full"]

[dev-dependencies]
bracket-color = "0.8"
rand = "0.8"

[dev-dependencies.snake-logic]
# path = "../snake-logic"
git = "https://github.com/EdJoPaTo/snake-logic"
tag = "v0.3.0"
