[package]
name = "esp-wlan-led-matrix-client"
description = "Control an espPixelmatrix via Rust"
version = "0.1.0"
license = "MIT"
repository = "https://github.com/EdJoPaTo/esp-wlan-led-matrix-client"
authors = ["EdJoPaTo <esp-wlan-led-matrix-client-rust@edjopato.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
# See https://doc.rust-lang.org/rustc/codegen-options/index.html
codegen-units = 1
lto = true

[features]
default = ["sync", "async-tokio"]
sync = ["bufstream"]
async-tokio = ["tokio"]

[[example]]
name = "fill"
required-features = ["sync"]

[[example]]
name = "snake"
required-features = ["rand", "sync", "bracket-color", "snake-logic"]

[[example]]
name = "speedtest"
required-features = ["rand", "sync"]

[[example]]
name = "stars"
required-features = ["rand", "async-tokio"]

[dependencies]

[dependencies.bracket-color]
version = "0.8"
optional = true

[dependencies.bufstream]
version = "0.1"
optional = true

[dependencies.rand]
version = "0.8"
optional = true

[dependencies.tokio]
version = "1"
features = ["full"]
optional = true

[dependencies.snake-logic]
#path = "../snake-logic"
git = "https://github.com/EdJoPaTo/snake-logic"
optional = true
